# @package _global_
dataset_name: Lobule_parietal_sup_right_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/Lobule_parietal_sup./mask/Rskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 41, 45, 48]
subjects_to_remove: None
remove_subjects: False