# @package _global_
dataset_name: OCCIPITAL_left_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Lskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/OCCIPITAL/mask/Lskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 35, 28, 42]
subjects_to_remove: None
remove_subjects: False