# @package _global_
dataset_name: SC-sylv_left_UKB
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.C.-sylv./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.C.-sylv./mask/Lskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 38, 36, 49]
subjects_to_remove: None
remove_subjects: False