# @package _global_
dataset_name: SFinf-BROCA-SPeCinf_left_UKB
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.F.inf.-BROCA-S.Pe.C.inf./mask/Lskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 25, 41, 44]
subjects_to_remove: None
remove_subjects: False