# @package _global_
dataset_name: SFinter-SFsup_right_UKB
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.F.inter.-S.F.sup./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.F.inter.-S.F.sup./mask/Rskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 31, 50, 53]
subjects_to_remove: None
remove_subjects: False