# @package _global_
dataset_name: SFmarginal-SFinfant_left_UKB
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.F.marginal-S.F.inf.ant./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.F.marginal-S.F.inf.ant./mask/Lskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 34, 32, 39]
subjects_to_remove: None
remove_subjects: False