# @package _global_
dataset_name: SFmedian-SFpoltr-SFsup_left_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.median-S.F.pol.tr.-S.F.sup./mask/Lskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 31, 54, 58]
subjects_to_remove: None
remove_subjects: False