# @package _global_
dataset_name: SPeC_right_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.Pe.C./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.Pe.C./mask/Rskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 38, 40, 50]
subjects_to_remove: None
remove_subjects: False