# @package _global_
dataset_name: STi-SOTlat_left_UKB
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.i.-S.O.T.lat./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.i.-S.O.T.lat./mask/Lskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 34, 64, 53]
subjects_to_remove: None
remove_subjects: False