# @package _global_
dataset_name: STs_right_UKB
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.s./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.s./mask/Rskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 24, 52, 51]
subjects_to_remove: None
remove_subjects: False