# @package _global_
dataset_name: STsbr_left_UKB
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.s.br./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.s.br./mask/Lskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 29, 40, 41]
subjects_to_remove: None
remove_subjects: False