defaults:
 - _self_
 - dataset_localization: neurospin
 - dataset: cristobal/UKB/STs_right
 #- dataset: cristobal/SC-sylv_right_UKB
 #- dataset: cristobal/hcp/FCLp-subsc-FCLa-INSULA_left
 # configs/config.yaml
 - model: BetaVAE
 - trainer: trainer
 - loss: CrossEntropy
