# @package _global_
dataset_name: COLLATERAL_right_HCP
data_dir: ${dataset_folder}/hcp/crops/2mm/F.Coll.-S.Rh./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/hcp/crops/2mm/F.Coll.-S.Rh./mask/Rskeleton_subject.csv
in_shape: [1, 34, 62, 41]
subjects_to_remove: None
remove_subjects: False