# @package _global_
dataset_name: S.C.-S.Pe.C._left_HCP
data_dir: ${dataset_folder}/hcp/crops/2mm/S.C.-S.Pe.C./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/hcp/crops/2mm/S.C.-S.Pe.C./mask/Lskeleton_subject.csv
in_shape: [1, 38, 49, 52]
subjects_to_remove: None
remove_subjects: False