# @package _global_
dataset_name: S.C.-S.Pe.C._right_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-S.Pe.C./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-S.Pe.C./mask/Rskeleton_subject.csv
in_shape: [1, 42, 47, 51]
subjects_to_remove: None
remove_subjects: False