# @package _global_
dataset_name: S.F.int.-F.C.M.ant._right_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.int.-F.C.M.ant./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.F.int.-F.C.M.ant./mask/Rskeleton_subject.csv
in_shape: [1, 17, 57, 54]
subjects_to_remove: None
remove_subjects: False