# @package _global_
dataset_name: SC-sylv_right_ABCD
data_dir: /neurospin/dico/data/deep_folding/current/datasets/ABCD/crops/2mm/S.C.-sylv./mask/Rskeleton.npy
subject_dir: /neurospin/dico/data/deep_folding/current/datasets/ABCD/crops/2mm/S.C.-sylv./mask/Rskeleton_subject.csv
save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 42, 34, 49]
subjects_to_remove: None
remove_subjects: False