# @package _global_
dataset_name: TEMPORAL_right_HCP
data_dir: ${dataset_folder}/hcp/crops/2mm/S.T.s./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/hcp/crops/2mm/S.T.s./mask/Rskeleton_subject.csv
in_shape: [1, 24, 52, 51]
subjects_to_remove: None
remove_subjects: False