# @package _global_
dataset_name: TEMPORAL_right_epilepsy_PBS
data_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.s./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/epilepsy_PBS/crops/2mm/S.T.s./mask/Rskeleton_subject.csv
in_shape: [1, 24, 52, 51]
subjects_to_remove: None
remove_subjects: False