# @package _global_
dataset_name: FCLp-subsc-FCLa-INSULA_right_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/F.C.L.p.-subsc.-F.C.L.a.-INSULA./mask/Rskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 37, 44, 51]
subjects_to_remove: None
remove_subjects: False
