# @package _global_
dataset_name: FCMpost-SpC_left_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/F.C.M.post.-S.p.C./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/F.C.M.post.-S.p.C./mask/Lskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 16, 45, 31]
subjects_to_remove: None
remove_subjects: False
