# @package _global_
dataset_name: FIP-FIPPoCinf_left_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/F.I.P.-F.I.P.Po.C.inf./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/F.I.P.-F.I.P.Po.C.inf./mask/Lskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 41, 53, 44]
subjects_to_remove: None
remove_subjects: False
