# @package _global_
dataset_name: Lobule_parietal_sup_left_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/Lobule_parietal_sup./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/Lobule_parietal_sup./mask/Lskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 40, 47, 46]
subjects_to_remove: None
remove_subjects: False
