# @package _global_
dataset_name: SC-SPoC_right_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/S.C.-S.Po.C./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/S.C.-S.Po.C./mask/Rskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 42, 43, 49]
subjects_to_remove: None
remove_subjects: False
