# @package _global_
dataset_name: SCall_right_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/S.Call./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/S.Call./mask/Rskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 15, 52, 34]
subjects_to_remove: None
remove_subjects: False
