# @package _global_
dataset_name: ScCal-SLi_right_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/Sc.Cal.-S.Li./mask/Rskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 26, 42, 44]
subjects_to_remove: None
remove_subjects: False
