# @package _global_
dataset_name: SFint-SR_right_PEPR_Marseille
data_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/S.F.int.-S.R./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/PEPR_Marseille/crops/2mm/S.F.int.-S.R./mask/Rskeleton_subject.csv
#save_dir: /neurospin/dico/fred/Runs/01_betaVAE/Output
in_shape: [1, 17, 57, 59]
subjects_to_remove: None
remove_subjects: False
